
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  11/10/2012 1:35:38 AM
 * Compiled by: vestben-PC\vestben
 * Source: C:\Users\vestben\Documents\My Web Sites\Empty Site1\game\Map.coffee      
 * -------------------------------------------------------------------------*/


var Map;

Map = (function() {

  function Map() {
    console.log("derp");
  }

  return Map;

})();
