
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  11/10/2012 1:34:57 AM
 * Compiled by: vestben-PC\vestben
 * Source: C:\Users\vestben\Documents\My Web Sites\Empty Site1\game\Player.coffee      
 * -------------------------------------------------------------------------*/


var Player;

Player = (function() {

  function Player() {
    console.log("player");
  }

  Player.prototype.tick = function() {};

  return Player;

})();
