
/* -------------------------------------------------------------------------
 * !!! AUTOMATICALLY GENERATED CODE !!!
 * -------------------------------------------------------------------------
 * This file was automatically generated by the OrangeBits compiler.  
 * Compiled on:  11/10/2012 11:04:55 AM
 * Compiled by: vestben-PC\vestben
 * Source: C:\Users\vestben\Documents\My Web Sites\TowerDefense\game\Tower.coffee      
 * -------------------------------------------------------------------------*/


var Tower;

Tower = (function() {

  function Tower(location, type) {
    console.log("something");
  }

  return Tower;

})();
